### ISSUE TITLE
Dataconverter fail with '2000-10-30 15:40'

### ISSUE THREAD

**Issue by 1letter** [plone/plone.app.z3cform#148]
```
Error in test test_data_converter (plone.app.z3cform.tests.test_widgets.DatetimeWidgetTests)
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/opt/development/collective/plone.app.z3cform/plone/app/z3cform/tests/test_widgets.py", line 322, in test_data_converter
    converter.toFieldValue('2000-10-30 15:40'),
  File "/opt/development/collective/plone.app.z3cform/plone/app/z3cform/converters.py", line 115, in toFieldValue
    ret = datetime(*map(int, value))
ValueError: invalid literal for int() with base 10: '30 15:40'
```
side note: tests in collective.easyform fails

**Comment by jensens** [comment]
The value splits on`T`, means correct input is `2000-10-30T15:40` - see https://www.w3.org/TR/NOTE-datetime.

**Comment by petschki** [comment]
Is this still an issue? There was a PR which sounds related https://github.com/plone/plone.app.z3cform/pull/151

**Comment by jensens** [comment]
I am not 100% sure about the OPs problem, but it looks like this is solved/hardened with my referenced PR.
I close this now, reopen if I am wrong.
